name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: '0 18 * * *' # Executa todo dia às 18:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vitosdeveloper/vitosdeveloper-readmemd
          token: ${{ secrets.TOKEN }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: vitosdeveloper
          SETTING_JSON: conf/github-profile-3d-contrib.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commitar."
          else
            git commit -m "generated new image"
            git push --force origin main
          fi
